version: '3.8'
services:
  redis-server:
    container_name: redis-server
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  node-server:
    container_name: node-server
    image: game:dev
    environment:
      - ENVIRONMENT=dev
    depends_on:
      - redis-server
    ports:
      - 8000:8000
    links:
      - redis-server
    volumes:
      - ../:/src
volumes:
  redis:
    driver: local
